#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#000000'
    background = '#d3d7cf'
    # leading_diamond = '╭─'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#e4e4e4'
    background = '#3465a4'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#000000'
    background = '#4e9a06'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#4e9a06{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#ffffff'
    background = '#689f63'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}  '

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'go'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#111111'
    background = '#00acd7'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'julia'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#111111'
    background = '#4063D8'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#111111'
    background = '#FFDE57'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = false

  [[blocks.segments]]
    type = 'azfunc'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#ffffff'
    background = '#FEAC19'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    type = 'aws'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#ffffff'
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "jan" .Profile}}#f1184c{{end}}']
    template = ' {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}  '

    [blocks.segments.properties]
      display_default = false

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#111111'
    background = '#ffff66'
    template = '  '

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#000000'
    background = '#c4a000'
    template = ' {{ .FormattedMs }}  '

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#d3d7cf'
    background = '#000000'
    background_templates = ['{{ if gt .Code 0 }}#cc2222{{ end }}']
    template = ' {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    foreground = '#000000'
    background = '#d3d7cf'
    template = ' {{ .CurrentDate | date .Format }}  '

